### ISSUE TITLE
Instructions for installing specific dotfiles are incorrect.

### ISSUE THREAD

**Issue by 5HT2** [ClydeDroid/dotfiles#1]
```
[bella@archhost ~]$ ls .dotfiles/
HEAD  branches  config  description  hooks  info  objects  packed-refs  refs
[bella@archhost ~]$ alias dotfiles='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
[bella@archhost ~]$ dotfiles config --local status.showUntrackedFiles no
[bella@archhost ~]$ dotfiles checkout .config/polybar/config
error: pathspec '.config/polybar/config' did not match any file(s) known to git
```

**Comment by 5HT2** [comment]
Oh. Just realized it's because the `git clone --bare git@github.com:ClydeDroid/dotfiles.git $HOME/.dotfiles` command never downloads the literal . files from the repo.
```
[bella@archhost .dotfiles]$ ls -l
total 36
-rw-r--r-- 1 bella bella   23 Jan  4 22:29 HEAD
drwxr-xr-x 2 bella bella 4096 Jan  4 22:29 branches
-rw-r--r-- 1 bella bella  130 Jan  4 22:29 config
-rw-r--r-- 1 bella bella   73 Jan  4 22:29 description
drwxr-xr-x 2 bella bella 4096 Jan  4 22:29 hooks
drwxr-xr-x 2 bella bella 4096 Jan  4 22:29 info
drwxr-xr-x 4 bella bella 4096 Jan  4 22:29 objects
-rw-r--r-- 1 bella bella  105 Jan  4 22:29 packed-refs
drwxr-xr-x 4 bella bella 4096 Jan  4 22:29 refs
[bella@archhost .dotfiles]$ la
.  ..  HEAD  branches  config  description  hooks  info  objects  packed-refs  refs
```

Looked on `man` what --bare does, and guess what, it ignores .dotfiles! Might wanna fix that :p

**Comment by delet-this** [comment]
The following seems to work:
`dotfiles checkout HEAD .config/polybar/config`

**Comment by nickclyde** [comment]
Thanks for finding the correct command @delet-this! I'll update the README.

@S-B99 sorry for the confusion! The reason I used a bare repo is that it lets me manage my dotfiles directly from my home directory without any symlinks. More info here: http://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/ and here https://github.com/ifohancroft/.dotfiles-readme
